export const ROCKET_MOUSE_RUN = 'rocket-mouse-run'
export const ROCKET_FLAMES_ON = 'rocket-flames-on'
export const ROCKET_MOUSE_FALL = 'rocket-mouse-fall'
export const ROCKET_MOUSE_FLY = 'rocket-mouse-fly'
export const ROCKET_MOUSE_DEAD = 'rocket-mouse-dead'
